# Configuration for LLaMA-specific circuit discovery with lower thresholds

# Model settings - LLaMA only
models:
  - "meta-llama/Llama-2-7b-chat-hf"

# Categories (matching available activation files)
categories: ["deception", "harassment", "harmful", "hate", "illegal", "privacy", "self-harm", "sexual", "unethical", "violence"]

# Activation collection (matching available SAE layers)
activation_layers:
  - "residuals_10"
  - "mlp_11"
  - "residuals_15"

# Circuit discovery parameters - VERY LOW thresholds for LLaMA
node_threshold: 0.0001  # Much lower to handle precision issues
edge_threshold: 0.00001 # Much lower to handle precision issues
aggregation_method: "none"
attribution_method: "stats"

# Runtime settings
device: "cuda"
batch_size: 4
result_dir: "results"
train_saes: false

# Output settings
create_visualizations: true