# LLaMA-2 Circuit Discovery Configuration
# This configuration was used to generate the final results in the repository

# Model settings
models:
  - "meta-llama/Llama-2-7b-chat-hf"

# Categories (all OR-Bench refusal categories)
categories: ["deception", "harassment", "harmful", "hate", "illegal", "privacy", "self-harm", "sexual", "unethical", "violence"]

# Activation collection layers (matching trained SAEs)
activation_layers:
  - "residuals_10"
  - "mlp_11"
  - "residuals_15"

# Circuit discovery parameters (optimized for interpretable circuits)
node_threshold: 0.8      # High threshold for small, interpretable circuits (26-84 nodes)
edge_threshold: 0.01     # Low threshold to capture meaningful connections
aggregation_method: "none"
attribution_method: "stats"

# Runtime settings
device: "cuda"
batch_size: 4
result_dir: "results"
train_saes: false

# Output settings
create_visualizations: true